const fs = require('fs');
const path = require('path');

// Load environment variables from .env file
require('dotenv').config();

// Generate Firebase config from environment variables
const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY,
  authDomain: process.env.FIREBASE_AUTH_DOMAIN,
  projectId: process.env.FIREBASE_PROJECT_ID,
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.FIREBASE_APP_ID
};

// Generate app config from environment variables
const appConfig = {
  donationUrl: process.env.DONATION_URL || 'https://www.buymeacoffee.com/YOUR_USERNAME'
};

// Check if all required environment variables are present
const requiredVars = ['FIREBASE_API_KEY', 'FIREBASE_AUTH_DOMAIN', 'FIREBASE_PROJECT_ID', 'FIREBASE_STORAGE_BUCKET', 'FIREBASE_MESSAGING_SENDER_ID', 'FIREBASE_APP_ID'];
const missingVars = requiredVars.filter(varName => !process.env[varName]);

if (missingVars.length > 0) {
  console.error('Missing required environment variables:');
  missingVars.forEach(varName => console.error(`  - ${varName}`));
  console.error('\nPlease update your .env file with the missing variables.');
  process.exit(1);
}

// Optional configuration warnings
if (!process.env.DONATION_URL || process.env.DONATION_URL.includes('YOUR_USERNAME')) {
  console.warn('\nWarning: DONATION_URL not configured or contains placeholder.');
  console.warn('Please update DONATION_URL in your .env file with your actual Buy Me a Coffee URL.');
}

// Generate the Firebase config file for REST API usage
const configContent = `// Firebase configuration - Generated from .env file
// DO NOT EDIT THIS FILE DIRECTLY - Edit .env instead and run 'npm run build:config'

// Firebase configuration object for REST API usage
const FIREBASE_CONFIG = ${JSON.stringify(firebaseConfig, null, 2)};

// App configuration object
const APP_CONFIG = ${JSON.stringify(appConfig, null, 2)};

// Make config available globally for auth and sync managers
if (typeof window !== 'undefined') {
  window.FIREBASE_CONFIG = FIREBASE_CONFIG;
  window.APP_CONFIG = APP_CONFIG;
  console.log('Firebase REST API configuration loaded for project:', FIREBASE_CONFIG.projectId);
}

// Export for use in other modules (Node.js/testing)
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { 
    FIREBASE_CONFIG, 
    APP_CONFIG, 
    firebaseConfig: FIREBASE_CONFIG, 
    appConfig: APP_CONFIG 
  };
}
`;

// Write the generated config to the firebase directory
const configPath = path.join(__dirname, 'firebase', 'firebase-config.js');
fs.writeFileSync(configPath, configContent);

console.log('Firebase configuration generated successfully from .env file');
