const fs = require('fs');
const path = require('path');

// Load environment variables from .env file
require('dotenv').config();

// Generate Firebase config from environment variables
const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY,
  authDomain: process.env.FIREBASE_AUTH_DOMAIN,
  projectId: process.env.FIREBASE_PROJECT_ID,
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.FIREBASE_APP_ID
};

// Check if all required environment variables are present
const requiredVars = ['FIREBASE_API_KEY', 'FIREBASE_AUTH_DOMAIN', 'FIREBASE_PROJECT_ID', 'FIREBASE_STORAGE_BUCKET', 'FIREBASE_MESSAGING_SENDER_ID', 'FIREBASE_APP_ID'];
const missingVars = requiredVars.filter(varName => !process.env[varName]);

if (missingVars.length > 0) {
  console.error('Missing required environment variables:');
  missingVars.forEach(varName => console.error(`  - ${varName}`));
  console.error('\nPlease update your .env file with the missing variables.');
  process.exit(1);
}

// Generate the Firebase config file
const configContent = `// Firebase configuration - Generated from .env file
// DO NOT EDIT THIS FILE DIRECTLY - Edit .env instead and run 'npm run build:config'

const firebaseConfig = ${JSON.stringify(firebaseConfig, null, 2)};

// Initialize Firebase with proper error handling
function initializeFirebaseApp() {
  try {
    if (typeof firebase !== 'undefined' && typeof window !== 'undefined' && !firebase.apps.length) {
      firebase.initializeApp(firebaseConfig);
      console.log('Firebase initialized successfully');
    }
  } catch (error) {
    console.error('Failed to initialize Firebase:', error);
  }
}

// Wait for Firebase to be available before initializing
if (typeof firebase !== 'undefined') {
  initializeFirebaseApp();
} else {
  // Wait for DOM content to be loaded and Firebase to be available
  if (typeof document !== 'undefined') {
    document.addEventListener('DOMContentLoaded', function() {
      if (typeof firebase !== 'undefined') {
        initializeFirebaseApp();
      } else {
        console.error('Firebase SDK not loaded');
      }
    });
  }
}

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { firebaseConfig };
}
`;

// Write the generated config to the firebase directory
const configPath = path.join(__dirname, 'firebase', 'firebase-config.js');
fs.writeFileSync(configPath, configContent);

console.log('Firebase configuration generated successfully from .env file');
